### ISSUE TITLE
brew install tale-cli报错，请帮忙解决一下

### ISSUE THREAD

**Issue by gofenix** [otale/tale-cli#1]
99-1-186-172:tale zhuzhenfeng$ brew install tale-cli
Error: No available formula with the name "tale-cli" 
==> Searching for a previously deleted formula...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
==> Searching local taps...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.

**Comment by hellokaton** [comment]
传到外网了，直接下载就可以了
